import sqlite3

from utils.validators import (
    validate_rating,
    validate_description,
    validate_menu_choice,
    validate_non_empty,
    validate_optional_mobile,
)

from utils.display import (
    print_header,
    print_footer,
    print_separator,
    print_success,
    print_error,
    press_enter,
)

from database.feedback_db import (
    FEEDBACK_CATEGORIES,
    FEEDBACK_STATUSES,
    save_feedback,
    view_feedback,
    search_feedback,
    update_feedback,
    delete_feedback,
    print_guest_satisfaction_report,
)


def _select_category():
    print("\nFeedback Categories:")
    for index, category in enumerate(FEEDBACK_CATEGORIES, start=1):
        print(f"{index}. {category}")

    choice = validate_menu_choice(
        "Select Category : ",
        [str(index) for index in range(1, len(FEEDBACK_CATEGORIES) + 1)]
    )
    return FEEDBACK_CATEGORIES[int(choice) - 1]


def _select_status(default="Open"):
    print("\nFeedback Status:")
    for index, status in enumerate(FEEDBACK_STATUSES, start=1):
        print(f"{index}. {status}")

    choice = validate_menu_choice(
        f"Select Status ({default}) : ",
        [str(index) for index in range(1, len(FEEDBACK_STATUSES) + 1)]
    )
    return FEEDBACK_STATUSES[int(choice) - 1]


def _feedback_date_optional():
    while True:
        value = input("Follow-up Date (DD-MM-YYYY, optional) : ").strip()
        if not value:
            return None
        from datetime import datetime
        try:
            return datetime.strptime(value, "%d-%m-%Y").strftime("%d-%m-%Y")
        except ValueError:
            print_error("Invalid date. Use DD-MM-YYYY format.")



def _select_follow_up_method():
    print("\nFollow-up Methods:")
    for index, method in enumerate(("Call", "WhatsApp", "Email"), start=1):
        print(f"{index}. {method}")
    choice = validate_menu_choice("Select Follow-up Method : ", ["1", "2", "3"])
    return ("Call", "WhatsApp", "Email")[int(choice) - 1]


def _select_follow_up_status(default="Pending"):
    print("\nFollow-up Status:")
    print("1. Pending")
    print("2. Completed")
    choice = validate_menu_choice(f"Select Follow-up Status ({default}) : ", ["1", "2"])
    return ("Pending", "Completed")[int(choice) - 1]


def _add_feedback():
    # Feedback IDs are generated by the system; guests/staff do not type them.
    customer_id = input("Customer ID (optional) : ").strip().upper()

    if customer_id:
        customer_name = ""
        mobile = ""
    else:
        customer_name = validate_non_empty("Customer Name : ")
        mobile = validate_optional_mobile("Mobile (optional) : ")
        if not mobile:
            raise ValueError("Mobile is required when Customer ID is not provided.")

    rating = validate_rating("Rating (1-5) : ")
    category = _select_category()
    review = validate_description("Review : ")

    complaint_choice = validate_menu_choice(
        "Complaint? (1=No, 2=Yes) : ",
        ["1", "2"]
    )

    complaint = None
    issue = None
    resolution = None
    status = "Closed"
    follow_up_date = None
    follow_up_required = 0
    follow_up_method = None
    follow_up_status = None
    follow_up_notes = None

    if complaint_choice == "2":
        # Guest-facing capture stops at the complaint statement.
        # Issue/resolution/status/follow-up are internal staff workflow fields.
        complaint = validate_description("Complaint : ")
        status = "Open"

    feedback_id = save_feedback(
        None,
        customer_name,
        mobile,
        rating,
        review,
        customer_id=customer_id or None,
        category=category,
        complaint=complaint,
        issue=issue,
        resolution=resolution,
        status=status,
        follow_up_date=follow_up_date,
        follow_up_required=follow_up_required,
        follow_up_method=follow_up_method,
        follow_up_status=follow_up_status,
        follow_up_notes=follow_up_notes,
        allow_pending_complaint=True,
    )

    print_success("Feedback Saved Successfully.")
    print("Feedback ID :", feedback_id)
    print("Category    :", category)
    print("Rating      :", rating, "/ 5")
    print("Status      :", status)
    if complaint:
        print("Complaint   :", complaint)
        print("Next Action : Staff can manage Issue, Resolution, Status and Follow-up from Update Feedback.")
    else:
        print("Complaint   : No")

def feedback_management():
    while True:
        print_header("FEEDBACK + GUEST EXPERIENCE")

        print("1. Add Feedback")
        print("2. View Feedback")
        print("3. Search Feedback")
        print("4. Update Feedback / Complaint Management")
        print("5. Delete Feedback")
        print("6. Guest Satisfaction Summary")
        print("7. Back")

        print_separator()
        print_footer()

        choice = validate_menu_choice(
            "Enter Choice : ",
            ["1", "2", "3", "4", "5", "6", "7"]
        )

        try:
            if choice == "1":
                _add_feedback()

            elif choice == "2":
                view_feedback()

            elif choice == "3":
                search_feedback()

            elif choice == "4":
                update_feedback()

            elif choice == "5":
                delete_feedback()

            elif choice == "6":
                print_guest_satisfaction_report()

            elif choice == "7":
                break

        except PermissionError as exc:
            print_error(f"LOGIN REQUIRED: {exc}")
            print("Please login with an authorized account and try again.")
        except sqlite3.Error as exc:
            print_error(f"Database operation failed: {exc}")
            print("The operation was not completed.")
        except ValueError as exc:
            print_error(str(exc))

        if choice != "7":
            press_enter()
